spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${POSTGRE}
    password: ${2052}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
